### ISSUE TITLE
Localization 

### ISSUE THREAD

**Issue by leipert** [sharkdp/insect#104]
In the context of #86 one could think about localization. For example in German million, billion etc. are abbreviated like this:

1. `Mio.` = Million
2. `Mrd.` (Milliarde) = Billion
3. `Bio.` (Billion) = Trillion
4. `Brd.` (Billarde) = Quadrillion

**Comment by sharkdp** [comment]
Thank you for the feedback.

There's also other things that are localization-dependent, like the decimal mark (`.` vs `,`). To be honest (also speaking as a German here), I'd rather have a predictable and strict syntax for the calculator (that is based on the English language) compared to something that is properly 'internationalized' but requires me to know which mode I'm in. This is only a personal opinion, of course, but I'm always surprised if `3.145` is suddenly parsed as `3145` because `.` is just the thousands-separator in German.

What do you think?

**Comment by leipert** [comment]
I do not know. I think the Million, etc. is discussable. Depending on the target group the configuration of the decimal separator might be an good idea. Especially if you'd like to provide the web version to let's say a class of German/French physics/chemistry students.

**Comment by sharkdp** [comment]
Okay, I think we could implement this to some extend via user-defined settings (see #107). A German user could create the file `~/.config/insectrc` with settings similar to:
```
set decimal_separator ","
Million = 1e6
Milliarde = 1e9
Billion = 1e12
```

**Comment by leipert** [comment]
That sounds like a nice idea. I think we could close this issue and write down a comprehensive list in #107 what should be "user configurable".

**Comment by sharkdp** [comment]
Yes, thanks.
