### ISSUE TITLE
Support for blood sugar units

### ISSUE THREAD

**Issue by leipert** [sharkdp/insect#105]
There are 2 ways to measure blood sugar [[1]](https://en.wikipedia.org/wiki/Blood_sugar#Units)

Trying to convert between the both raises an error.

```
≫ 70 mg/dl to mmol/l
  70 mg / dL ➞ mmol / L
  Conversion error:
    Cannot convert unit mg/dL (base units: kg·m⁻³)
                to unit mmol/L (base units: mol·m⁻³)
```

Here is the conversion formula:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/dccdaecb6631ca6880afc6af13ed47fa2f61b081)

**Comment by sharkdp** [comment]
Thank you for the feedback!

Insect only supports conversions that are mathematically correct, that is, if the physical dimensions are the same. As the error message indicates, the quantity on the left is a mass-density (`kg·m⁻³`) while the quantity on the right is a 'substance'-density (`mol·m⁻³`).

In order to convert between those two quantities, we need the [molecular mass of Glucose](https://en.wikipedia.org/wiki/Glucose) in `g/mol`:
```
>>> mol_mass = 180.16 g/mol

  mol_mass = 180.16 g/mol

>>> 70 mg/dl / mol_mass -> mmol/l

  (70 mg / dL) / mol_mass ➞ mmol / L

   = 3.88544 mmol/L
```

**Comment by leipert** [comment]
Yeah, probably not the best units to add. I think this issue can be closed for know. It is documented for now and everyone who needs to convert from one to the other.
