### ISSUE TITLE
Show user-defined variables (+ ans)

### ISSUE THREAD

**Issue by desmond-dsouza** [sharkdp/insect#131]
On the web-ui, a separate panel showing all current user-defined variables (+ ans) with their values would be quite useful. Alternately, a command to list these would nice (**list** also shows all built-in constants).

Great work, thanks for sharing!

**Comment by sharkdp** [comment]
> On the web-ui, a separate panel showing all current user-defined variables (+ ans) with their values would be quite useful.

I think would like to keep the web-ui as simple as possible, but we could definitely experiment with alternative front-ends (for now, that could only be a copy of `web/index.html`).

> Alternately, a command to list these would nice (list also shows all built-in constants).

Sounds good! Let me know if you have any ideas for the syntax (sth like `list user`?).

> Great work, thanks for sharing!

Thank you for the feedback!

**Comment by sharkdp** [comment]
@desmond-dsouza 

Here's another idea: what if we just keep a single command (`list`), but show the user-defined variables in a separate list below the built-in constants. This way, they would always be immediately visible without scrolling.

(Pro tip: you can also type `ls` or `ll` instead of `list`, if you use this often)

**Comment by sharkdp** [comment]
Closing this as there is no further feedback.
