### ISSUE TITLE
Add more Operators + Remove false copied characters

### ISSUE THREAD

**Issue by VSilverstein** [sharkdp/insect#132]
Hello Insect,
Found your project via [Alfred CLC](https://github.com/aviaryan/alfred-clc) and already love your work! :)
Can't really find any documentation for Insect and have three questions:
Is it possible that I can add some more Operators? And how?
Is it possible that I can change the Decimal from . to , ? And how?
Is it possible that I can remove false copied characters as { } and 〖 〗? And how?
Edit: Is it possible that I can change how many numbers after the Decimal it shows? And how?

Thanks a lot! :D Have been looking for this for two years xD

**Comment by sharkdp** [comment]
> Can't really find any documentation for Insect and have three questions:

The documentation is right [here](https://github.com/sharkdp/insect#documentation) in the README. The language reference is [also there](https://github.com/sharkdp/insect#reference).

> Is it possible that I can add some more Operators? And how?

Would you like to add operators at runtime? Or in general, as a new feature of Insect? Which operators are you missing?

> Is it possible that I can change the Decimal from . to , ? And how?

It's currently not possible, but has been initially considered to be configurable here: #107. I crossed it out because I don't think it will be realized anytime soon.

> Is it possible that I can remove false copied characters as { } and 〖 〗? And how?

No, that's not possible. Out of curiosity: where do you copy your calculations from?

Insect can also be used as a library, so it would be possible to define an alternative interface where that could be an additional feature, but I currently don't see why we should add this to the general interface.

> Edit: Is it possible that I can change how many numbers after the Decimal it shows? And how?

Also under discussion here: #107.

> Thanks a lot! :D Have been looking for this for two years xD

Thank you for the feedback! I'm glad you like it!

**Comment by VSilverstein** [comment]
> Would you like to add operators at runtime?

Just wanna add some *permanent* operators.

> Or in general, as a new feature of Insect?

Yes, a feature where it's possible to add some more operators.

> Which operators are you missing?

I need e.g. the "\bullet" from word equations.

> I crossed it out because I don't think it will be realized anytime soon.

Decimal from . to , and visa versa is a normal config in 99% of programs worldwide 🙂️

>> Is it possible that I can remove false copied characters as { } and 〖 〗? And how?

>No, that's not possible. Out of curiosity: where do you copy your calculations from?

It should be possible! :) I'm copying my calculations from Words Equation fields 🙂️

> Insect can also be used as a library, so it would be possible to define an alternative interface where that could be an additional feature, but I currently don't see why we should add this to the general interface.

Additional feature could be, in the config file: ignore characters =〖  & } & 〗& { 

**I'm a total noob when it comes to understanding #107, because I can't see a dummy guide** 😅️

**Comment by sharkdp** [comment]
To be honest, this seems like a very niche use case to me.

We already support three versions of the multiplication operator: `*`, `·` and `×`. Supporting `\bullet` seems very unnatural to me.

It sounds like you could possibly write a simple script that would replace `\bullet` by `*` and remove characters like `〖`, `}`, ... But I don't see this as a feature of Insect, sorry.

> Decimal from . to , and visa versa is a normal config in 99% of programs worldwide

I doubt it, but there is also other reasons why I would like to avoid this. Consider an input like this:
```
f(3,4)
```

Is this a function call to `f` with a single argument (the number *3,4* or *3.4*) or is this a function call to `f` with two arguments (*3* and *4*)? If you want this to be parsed as the former, you also have to introduce a new syntax for separating function arguments. I'd rather avoid ambiguities like this in the first place.

I'm from Germany, so I also use `,` as the decimal mark - but I don't think it's too hard to get used to `.` :smile:
