### ISSUE TITLE
Dummy Units

### ISSUE THREAD

**Issue by Twister915** [sharkdp/insect#136]
Having the ability to type things like:

```10 apples per classroom per school day * (10 school days) * (100 classrooms)```

or 

```1 dollar per person per hour * 100 people * 3 months```

would be great.

This isn't a particularly rigorous idea, but hopefully I've conveyed a good general idea.

**Comment by sharkdp** [comment]
This seems like a useful addition to me and has been requested a few times in the past. Other useful examples are: `px`/`pixels`, `dot`/`dots`, `piece`/`pieces`.

There are a few things that should be discussed first:

How do we add these "dummy units"?
- *Globally*: simply add a few useful units to the global list of units. This would be very easy to implement and the units could be used right away. The downside is that those units would be hard-coded and adding new units would require releasing a new version of Insect.
- *User-defined*: We add a new keyword and new units can be introduced via `define-unit apple apples` (or similar). This would be more flexible. However, units would always have to be defined first (although #107 would help here).

Do we need support for prefixes?
- For most of the given examples, I would not expect metric prefixes to work (`kilopersons`, `microdollars`, ..). However, `pixel` would be an example where prefixes would come in handy (`megapixel`). Given that this would probably be very hard to implement (for user-defined dummy units, anyway), I think we can safely ignore prefixes.

> `10 apples per classroom per school day * (10 school days) * (100 classrooms)`

I'm afraid this would have to be: `schoolday` or `school_day`.
Otherwise, it would be parsed as `school * day`.

**Comment by sharkdp** [comment]
@Twister915 Any thoughts on this?

**Comment by adius** [comment]
Actually I think for the beginning a global list wouldn't be to bad. I suspect there are several units which would greatly benefit from some hard coded shortcuts / defaults / extra functions (a la Celsius & Fahrenheit).

**Comment by sharkdp** [comment]
The following units are now supported:

- `dollars`, `dollar`, `USD`, `$`
- `dots`, `dot`
- `dpi`
- `euros`, `euro`, `EUR`, `€`
- `persons`, `person`, `people`
- `pieces`, `piece`
- `pixels`, `pixel`, `px`
- `ppi`
- `pound_force`, `lbf`

So calculations like these are possible now:

```
>>> 86€ / 17 people 

  86 EUR / 17 person

   = 5.05882 EUR/person
```

```
>>> resolution = sqrt((1920 px)^2 + (1080 px)^2)

  resolution = 2202.91 px

>>> resolution / 54 cm to ppi

  resolution / 54 cm ➞ px/in

   = 103.618 px/in
```

Hope this fits everyone's needs. Let me know what you think.
