### ISSUE TITLE
Can nexe (or other approach) convert insect to C/C++ source instead of compiling?

### ISSUE THREAD

**Issue by cesss** [sharkdp/insect#138]
I'd like to be able to use insect as a library in my C/C++ programs... if there was some way of "compiling" it into C/C++ it would be really great... can it be done with nexe or with other approaches?

**Comment by sharkdp** [comment]
> I'd like to be able to use insect as a library in my C/C++ programs...

Cool! :smile: 

> if there was some way of "compiling" it into C/C++ it would be really great... can it be done with nexe or with other approaches?

I'm not too familar with nexe, but I'm pretty sure that it cannot help with this problem. It just creates a standalone executable (basically it bundles all the JavaScript code and a Browser engine).

Insect is written in PureScript, which normally compiles to JavaScript. There is [an experimental backend](https://github.com/andyarvanitis/purescript-native) that allows the compiler to create C++11 code. However, I'm pretty sure that it would involve a lot of work to make Insect ready for compilation to C++, because all PureScript dependencies that depend on FFI JavaScript Code (like purescript-decimals) would need to be replaced by a C++ version.

If you are up to this challenge, I would be glad to advise you, but I will probably not find the time to work on this.

If you are on the search for an alternative, you might consider using libqalculate, which is written in C++ (Insect was inspired by Qalculate).

**Comment by cesss** [comment]
Precisely, I found insect just after visiting [this site](https://kkovacs.eu/cool-but-obscure-unix-tools) and finding at the bottom of the page a (mysterious to me) screenshot of an app called qalc. When I saw it, I exclaimed "**this** is what I want for my command line spreadsheet!!". Because the page is titled "obscure UNIX tools" I thought it would be abandoned code from decades ago, but I found that qalc is part of Qalculate, and very recent. Unfortunately it's copylefted and, because my aim is to use it as a library, I need the freedom of being able to use it through a non-copyleft license in case I need that at some point.

Another option I know of is "symengine" (the C++ port of the engine in the SymPy CAS). Of course, that's a CAS, so it's a big monster. It's non-copyleft, but, unfortunately, it's not complete yet (still at 0.3.0), and it still lacks Units. If it already had Units support, it could be a very good choice for me.

**Comment by sharkdp** [comment]
I see.

I'm going to close this as it seems that the initial questions is answered. Feel free to comment here or to open a new ticket in case there is something you'd like to discuss.

**Comment by cesss** [comment]
Thanks a lot for your comments, sharkdp, I'm considering to code it myself, from some simple notes to write a simple CAS. I believe it's doable. Merry Christmas, and thanks a lot!

**Comment by sharkdp** [comment]
Thank you and good luck with your project!
