### ISSUE TITLE
base command for direct conversion of desired units

### ISSUE THREAD

**Issue by ZumyT** [sharkdp/insect#184]
It would be nice to have a base command for direct conversion of desired units.
For example:
>> V -> base 
      = A⁻¹·kg·m²·s⁻³

**Comment by danieldjewell** [comment]
Not sure how it could (or would) impact things, but don't forget about the [2019 SI Redefinition](https://en.wikipedia.org/wiki/2019_redefinition_of_the_SI_base_units) ... Since eveything is now defined in terms of constants, one could theoretically deconstruct things into their base definitions....

Specifically for say the kilogram - which was previously defined as "the mass of the prototype kilogram" and is now defined in terms of constants... so, in that sense "1 kg" isn't a base unit from which others are defined, instead "1 kg" itself can be calculated based on the constants. Not sure how much of an impact this would have. Maybe something to think on.

**Comment by sharkdp** [comment]
Thank you for the reference. I know about the new SI definition. I don't really see how it is related to this issue. Some units (e.g. `second` and `meter`) were defined like this even before the redefinition.

The main "algorithm" behind this feature request is already implemented. Insect shows the "base representation" when a user tries to convert to a unit that is not compatible. For example:
```
>>> 1V -> s

  1 V ➞ s

  Conversion error:

    Cannot convert unit V (base units: A⁻¹·kg·m²·s⁻³)
                to unit s
```

**Comment by sharkdp** [comment]
Follow up ticket for Numbat: https://github.com/sharkdp/numbat/issues/116
