### ISSUE TITLE
Request: Lazy percentage calculation

### ISSUE THREAD

**Issue by evaryont** [sharkdp/insect#192]
This is a similar request to #147, and perhaps I'm not thinking of something, but it'd be very nice to support the following syntax:

```
>> 65% of 100

   = 65

>> 65% of 16GB

   = 10.4 GB
```

At the moment, the parser doesn't understand "of", which I hope means it'd be possible to implement without breaking compatibility:

```
≫ 65% of 100
  65 % (of × 100)
  Unknown identifier: of
```

**Comment by sharkdp** [comment]
Thank you for the feedback.

To be honest, I'm not a fan of the `xx% of …` syntax. In order to support this, `of` would need to be a special keyword that only accepts expressions of the type `<number>%` on the left-hand side. I don't it fits well with the rest of insects syntax.

One of insects design goals is to have a strict, unambiguous syntax (see https://github.com/sharkdp/insect#pros-and-cons). I would rather not overload the meaning of the `%` symbol, which is already used for modulo.

**Comment by evaryont** [comment]
Yeah, this would open the door to attempting to do a broader set of "human intention parsing", that is, trying to effectively parse sentences/speech into mathematical sentences. Even if you tried keeping it simple, that's awfully close to trying to emulate WolfamAlpha.
