### ISSUE TITLE
Fix 2 with currency

### ISSUE THREAD

**Issue by cup** [sharkdp/insect#206]
~~~
≫ 2.3$
  2.3 USD
   = 2.3 USD
~~~

https://insect.sh?q=2.3$

I would have expected the result to be `2.30 USD`

https://developer.mozilla.org/JavaScript/Reference/Global_Objects/Number/toFixed

**Comment by sharkdp** [comment]
Thank you for the feedback.

Insect is a numerical calculator and deals with floating point numbers. I would rather not like to add any special support for working with currencies such as making sure that we are dealing with numbers in cents.

**Comment by cup** [comment]
@sharkdp ok I understand that position

I think it would be simple to implement, but if its more difficult, or if you just are principled against it i respect that

Its not a huge issue, I appreciate the response

**Comment by sharkdp** [comment]
> [..] but if its more difficult [..]

I think so. To get this right would require a completely new way to handle numbers at the lowest level.

> [..] or if you just are principled against it [..]

I'm not completely against this, but I want Insect first and foremost to be a "*high precision* calculator with support for *physical* units" (see README). Currencies are currently only provided as "dummy" physical units because it can be quite convenient to use units like `USD/kg` or similar for quick calculations. But I don't want this to turn into a fully-blown tool for currency conversions etc. I'd rather focus on the core strength and keep the functionality limited.

> Its not a huge issue, I appreciate the response

Thanks!

**Comment by cup** [comment]
Great response. I hate feature creep and certainly don't want to add to that.

Thanks again
