### ISSUE TITLE
Support hexadecimal inputs

### ISSUE THREAD

**Issue by Qyriad** [sharkdp/insect#245]
A separate issue from #42 which is asking about bitwise operations, I'd love for the parser just to be able accept hexadecimal integers with 0x notation. I commonly use Insect to calculate between units of bytes, which I sometimes get in hex. It would be awesome if I didn't have to convert the value to decimal using some other tool before pasting it into Insect.

Getting *output* in hex would also be awesome, and *ideally* Insect would support arbitrary bases for inputs and outputs, but in this issue I'm only formally requesting support for hexadecimal inputs.

**Comment by sharkdp** [comment]
> A separate issue from #42 which is asking about bitwise operations, I'd love for the parser just to be able accept hexadecimal integers with 0x notation.

Yes, thanks. I would also love to have that.

> Getting _output_ in hex would also be awesome, and _ideally_ Insect would support arbitrary bases for inputs and outputs, but in this issue I'm only formally requesting support for hexadecimal inputs.

Have you seen the fork by @soupi where he implemented these features: https://soupi.github.io/insect/ ?

Adding this to insect in the current stage would be difficult, I believe. From time to time, I am thinking about a rewrite of Insect in order to design a few features differently and to fix some issues. Full hexadecimal/binary support would be one of the features I'd love to include in such a project.

**Comment by zhuzhzh** [comment]
> > A separate issue from #42 which is asking about bitwise operations, I'd love for the parser just to be able accept hexadecimal integers with 0x notation.
> 
> Yes, thanks. I would also love to have that. I think it _might_ be easy to add that to the parser.
> 
> > Getting _output_ in hex would also be awesome, and _ideally_ Insect would support arbitrary bases for inputs and outputs, but in this issue I'm only formally requesting support for hexadecimal inputs.
> 
> Have you seen the fork by @soupi where he implemented these features: https://soupi.github.io/insect/ ?
> 
> Adding this to insect in the current stage would be difficult, I believe. From time to time, I am thinking about a rewrite of Insect in order to design a few features differently and to fix some issues. Full hexadecimal/binary support would be one of the features I'd love to include in such a project.

Is there any update on this?

**Comment by mhmdanas** [comment]
@zhuzhzh which part of @sharkdp's comment are you referring to?

**Comment by zhuzhzh** [comment]
> @zhuzhzh which part of @sharkdp's comment are you referring to?

I refered to support hex input, like 0xff, 0b1101

**Comment by mhmdanas** [comment]
I plan to implement this in Insect 5.8.0, but I can't provide any guarantees.

**Comment by mhmdanas** [comment]
I was able to implement hex input successfully, and octal and binary too because why not? Anyway, in the process I faced a few questions (for brevity I'll refer to hex, octal, and binary input as "n-base input", notwithstanding that term's inaccuracy in this context):

1. Should we support fractional numbers inputted in n-base, e.g. 0xf.5?
  Personal opinion: yes, decimal.js is able to parse such numbers, and I think some people may find it useful.
2. decimal.js does not support power-of-ten exponents for n-base input (i.e. 0o5E2 does not work). It does, however, support power-of-two exponents (e.g. 0b11p5 = 3 * 2^5 = 96) for n-base input (but not for decimal numbers). Should we add that?
  Personal opinion: again, yes, this sounds like it could be useful.

**Comment by zhuzhzh** [comment]
> I was able to implement hex input successfully, and octal and binary too because why not? Anyway, in the process I faced a few questions (for brevity I'll refer to hex, octal, and binary input as "n-base input", notwithstanding that term's inaccuracy in this context):
> 
>     1. Should we support fractional numbers inputted in n-base, e.g. 0xf.5?
>        Personal opinion: yes, decimal.js is able to parse such numbers, and I think some people may find it useful.
> 
>     2. decimal.js does not support power-of-ten exponents for n-base input (i.e. 0o5E2 does not work). It does, however, support power-of-two exponents (e.g. 0b11p5 = 3 * 2^5 = 96) for n-base input (but not for decimal numbers). Should we add that?
>        Personal opinion: again, yes, this sounds like it could be useful.

1. I am one IC developer. I don't use 0xf.5 in my work.  For the floating number, we use IEEE754 (refer to https://en.wikipedia.org/wiki/IEEE_754).  but I think it's useful to support 0xff.35f4 for some persons.
2. it's reasonal not to support 0o5e2.  does it support 0xfp10=15*2^10?

**Comment by mhmdanas** [comment]
> does it support 0xfp10=15*2^10?

Yes, that syntax works for hex, octal, and binary numbers.

By the way, I would advise you not to quote a whole comment when replying to it, but only the relevant parts where needed. Quoting the whole comment makes scrolling that more tedious.

**Comment by zhuzhzh** [comment]
Got it.  looking forward to v5.8.0

**Comment by sharkdp** [comment]
This is now available in the web version: https://insect.sh/?q=0xffff

**Comment by zhuzhzh** [comment]
thanks, @mhmdanas! it works as expected!
does it support to convert between hex, dec, bin and oct?

**Comment by mhmdanas** [comment]
@zhuzhzh you're welcome.

>  does it support to convert between hex, dec, bin and oct?

No, only input is currently supported.
