### ISSUE TITLE
Precedence of units in parsing

### ISSUE THREAD

**Issue by hdgarrood** [sharkdp/insect#33]
This is possibly best illustrated by an example:

```
> 3m/4m
0.75m²
> 3m/(4m)
0.75
```

I was expecting to get `0.75` in both cases. Nice work on this by the way, it's a really nifty project!

**Comment by sharkdp** [comment]
Thank you for reporting this. I would also like it to parse `3m/4m` as `3m/(4m)`.

The problem is the following:
* When I am parsing `3m` as a combined entity (a `quantity`), the above behavior can be easily achieved. This is how to parser worked in the beginning. The problem with this approach is that `3m^x` will be parsed as `(3m)^x`, which is not what one would expect. Also, with this approach, one would need a separate expression parser for units alone (to parse things like `3kg*m/s^2`).
* I therefore decided to parse `3m` as an implicit multiplication (`3` times `m`). This immediately solves the problems mentioned above (powers of units and combined units). However, the problem is that `3m/4m` will now be parsed as `3*(m/4)*m` because division has a higher precedence than multiplication. If multiplication had a higher precedence, `3/4*5` would be parsed as `3/(4*5)`.

I think issue could be solved with the second approach, if the precedence chain would be:

... > *implicit* multiplication > division > explicit multiplication > ...

This would mean that `3/4x` would be parsed as `3/(4x)`, but `3/4*x` would be parsed as `(3/4)*x`.

I tried to implement this yesterday already, but couldn't get it to work. The problem is that I'm not sure how to treat the implicit multiplication independently from the explicit multiplication in the [expression parser](https://github.com/sharkdp/insect/blob/7cca4bd9bb186a5543d24d11f57e4db6c0478cc2/src/Insect/Parser.purs#L275-L279), but I will try it again.

> Nice work on this by the way, it's a really nifty project!

Thank you very much, that means a lot!

**Comment by hdgarrood** [comment]
Would something like this work?

```purescript
sepByMulExplicit ∷ P Expression
sepByMulExplicit = foldl1 (BinOp Mul) <$> sepByPow `sepBy1` mulOp

sepByDiv :: P Expression
sepByDiv = foldl1 (BinOp Div) <$> sepByMulExplicit `sepBy1` divOp

sepByMulImplicit :: P Expression
sepByMulImplicit = foldl1 (BinOp Mul) <$> sepByDiv `sepBy1` pure unit
```

**Comment by sharkdp** [comment]
Ohh... `pure unit` actually works! I only tried `string ""`, which introduced a lot of other problems (actually not sure what the difference is...).

The only drawback with this approach (that I can see right now) is that
```
4/3 pi r³
```
will now be parsed as `4/(3 pi r³)`, which is also unexpected. I'm afraid this can only be solved by a whitespace-aware parser(?).

**Comment by hdgarrood** [comment]
Ah nice :) I'm not sure what the difference is, I guess you'd have to look at the source.

I think that's how I would expect `4/3 pi r^3` to be parsed, personally, but I'm not a physicist. I think I'd be fine with having to write `(4/3) pi r^3`.

**Comment by sharkdp** [comment]
> I think that's how I would expect 4/3 pi r^3 to be parsed, personally

Hmm... :smile: In any case, I definitely prefer the new solution, even if it has this drawback (subjectively).

>I think I'd be fine with having to write (4/3) pi r^3.

Agreed. And `4/3 * pi * r^3` also works.

Fixed.
Thanks!
