### ISSUE TITLE
Cannot convert quantity of unit 'b' to a scalar

### ISSUE THREAD

**Issue by hrzafer** [sharkdp/insect#45]
```
> b = 5
5
> a = 5
5
> a+b
Cannot convert quantity of unit 'b' to a scalar
```

**Comment by ivanbakel** [comment]
b is reserved for bits, it seems. Confirm it by asking the value of `b`, which gives `1b`. The assignment of b (or any unit) to the environment seems to work, since `ls` shows the value pair correctly - the parsing makes the mistake. Either remove the assumption that u === 1u or forbid assigning to units and anything else reserved.

**Comment by sharkdp** [comment]
Yes, thanks for the explanation @ivanbakel. This is already tracked in #29.

**Comment by sharkdp** [comment]
This is now fixed:
```
> b = 5
5
> a = 5
5
> a+b
10
> B = 5
Parse error: The identifier 'B' is reserved for a physical unit at pos
ition 6
```
