### ISSUE TITLE
mb is treated as "millibytes"

### ISSUE THREAD

**Issue by tchajed** [sharkdp/insect#46]
Due to the uniform handling of SI prefixes, mb is unfortunately a millibyte, which is a pretty useless unit of measure:

```text
$ insect '1 mb -> bytes'
0.001b
```

This was pretty confusing to me, until I realized I needed to use `Mb` to get the desired unit (of mebibytes = 1000000 bytes, which is close enough).

Fixing this requires some special-casing of data storage-related units.

**Comment by sharkdp** [comment]
I'm not sure. I think I would like to keep the handling of SI prefixes consistent, even though I agree that "millibyte" is typically not a very useful unit.

But I just realized, that the standard way of writing "mega byte" [is actually "MB"](https://en.wikipedia.org/wiki/Megabyte) with a capital "B" (instead of "Mb"). Maybe we should just change byte to be "B". Then, "mB" would probably not expected to be mega byte. What do you think?

Also, I believe that #34 could help here, if the output had been:
```
> 1mb -> bytes

  1 milli byte -> bytes

  = 0.001b
````
