### ISSUE TITLE
Radians per second to Hertz conversion incorrect

### ISSUE THREAD

**Issue by sdonnan** [sharkdp/insect#50]
> 6rad/s -> hertz

        6Hz

Expected result: `0.9549Hz`

**Comment by itdaniher** [comment]
Not even a sig figs issue:

```
> 6.01 radians / second -> hertz
6.01Hz
```

**Comment by itdaniher** [comment]
`units` does the same thing:

```
You have: 6 radians per second
You want: hz
        * 6
        / 0.16666667
You have: 6 radians
You want:
        Definition: 6 radian
You have: radians
You want:
        Definition: radian = 1 radian
```

Radians is apparently a base unit as far as `insect` and `units` is concerned. We both expected radians as 2*pi, but this could also be expressed in degrees. No idea what's technically correct - if `insect` did base unit decomposition as `units` does, it would be fairly trivial for an end user to observe that `rad` resolves to a base unit, rather than a constant of 2*pi (tau) or a degrees angle conversion.

Also, your test case is semantically ambiguous, as ['rad' in the context of dimensional analysis](https://en.wikipedia.org/wiki/Rad_(unit)) is a depreciated unit of measure proportional to (radiation) energy in joules per kilogram:

```
You have: 1 rad
You want: 0.01 J / kg
        * 1
```

**Comment by itdaniher** [comment]
Even more interestingly - gnu units (and insect) are technically correct here, since 1995 "radian" is a unitless "SI-derived" parameter, so the shortcut taken by insect seems to be `radian = 1`.

Current behavior might violate the principle of least astonishment, but this doesn't seem to be a bug per-se. Obviously, interesting observation nevertheless!

**Comment by sdonnan** [comment]
Thanks for looking into this! I agree the behavior is definitely unexpected and can be explained by your interpretation of the radian unit definition.

Here is another surprising example which is related:

    > 360 degrees/sec -> Hz
      6.28319Hz

which doesn't really seem to make sense (I'd expect it to be `1Hz`), but can be explained by the radian behavior. 

As a user that does a lot of conversions with radians it would be more useful if the conventional radian conversions worked as expected. However, I will have to do some more digging to convince myself one way or the other is technically correct based on the unit definitions.

**Comment by sdonnan** [comment]
It seems like one would need to assume that any quantity measured in radians per second is an angular velocity in order to invoke the expected conversion (2 pi radians / s = 1 Hz). Pure dimensional analysis fails because (as you mentioned before) they technically have the same units (1/s).

So perhaps this should be a feature request for the calculator to abandon what I assume is a nice and tidy dimensional analysis approach to invoke a useful conversion in this corner case.

**Comment by sharkdp** [comment]
I would argue that the current behavior is not only technically correct, but also the expected behavior :smile:.

The confusing part is that *rotations per second* and [*angle per second*](https://en.wikipedia.org/wiki/Radian_per_second) (= rotational speed / angular velocity) have the same dimension (*1/time*), and can both be expressed in *Hz*. The reason is that both *number of rotations* and *angle* are dimensionless quantities.

If I am interpreting correctly, you are interested in *rotations per second*. If something rotates by *720°* in *1s*, you want the answer to be *2Hz*, because it rotates twice per second (correct me if I'm wrong). On the other hand, the quantities you entered (*6rad / s* or *360° / s*) are expressed in *angle per second*.

If you want *rotations per second*, you would have to compute the number of rotations first (*720° / 360° = 2*) and then divide by the time (*1s*):
```
> (720°/360°)/s -> Hz
2Hz
```

Same thing in radians: In your first example, you would need to compute the number of rotations (*6 rad / 2pi rad = 0.95493*) and then divide by *1s*:
```
> (6 rad / 2pi rad) / s -> Hz
0.95493Hz
```

> Even more interestingly - gnu units (and insect) are technically correct here, since 1995 "radian" is a unitless "SI-derived" parameter, so the shortcut taken by insect seems to be radian = 1.

Yes, exactly: https://en.wikipedia.org/wiki/SI_derived_unit#Derived_units_with_special_names

*360° = 2π rad = 2π*

**Comment by sharkdp** [comment]
@sdonnan Can this be closed?
