### ISSUE TITLE
Support KiB, MiB, GiB units

### ISSUE THREAD

**Issue by l2dy** [sharkdp/insect#81]
https://en.wikipedia.org/wiki/Mebibyte

**Comment by sharkdp** [comment]
Good suggestion, thanks!

**Comment by CMCDragonkai** [comment]
You could extend it with time units as well. Like gigabyte-seconds (for like memory usage, analogous to kilowatt-hour).

**Comment by sharkdp** [comment]
> You could extend it with time units as well. Like gigabyte-seconds (for like memory usage, analogous to kilowatt-hour).

Wouldn't that just be `GB s` (or `GiB s`), which is already supported?

**Comment by sharkdp** [comment]
This is now fully supported:
```
≫ 1 KiB -> B
   = 1024 B

≫ 120 GB -> GiB
   = 111.759 GiB

≫ 10 kibibyte + 1 mebibyte
   = 1034 KiB
```

**Comment by ngaloppo** [comment]
Unfortunately, GB can mean different things in different contexts, e.g. network transmission vs. memory storage. The former typically uses base 10, while the latter is usually in base 2, both when referring to mega/giga.

**Comment by sharkdp** [comment]
So what you are essentially saying is that in the context of memory storage, the unit `GB` - written exactly like this - is (wrongly) used for 2^30 bytes instead of 10^9 bytes? This would imply that it is used in a non-standardized way (`GiB` should be used instead of `GB`). What do you propose do about this?
