### ISSUE TITLE
your value for pi looks a little imprecise

### ISSUE THREAD

**Issue by Pomax** [sharkdp/insect#82]
While you certainly don't need a lot of decimal places for `pi` to do the right thing in most circumstances, you do need more than five. NASA's rule has been to use 15, which is precise enough to reliably plot planetary trajectories and only be off by a few centimeter by the time it leaves the solar system.

**Comment by Pomax** [comment]
looks like it's only the presentation of `pi` that's getting cut of... this is a bit surprising given that other computations (like 1/65355) show more decimals.

**Comment by sharkdp** [comment]
Yes, it's only the display. Insect shows 6 significant digits by default. That's why `pi` is displayed as `3.14159` and `1/65355` is displayed as `0.000015301`, i.e. `1.53010e-6`. The internal value of `pi` has ~80 digits: https://github.com/sharkdp/purescript-decimals/blob/master/src/Data/Decimal.js#L211-L213
